name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ github.sha }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: hanselchristopher001/password-generator:latest,hanselchristopher001/password-generator:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Flux CD config repository
      uses: actions/checkout@v4
      with:
        repository: Hansel-Christopher/password-generator
        token: ${{ secrets.GH_PAT }}
        path: flux-config

    - name: Update image tag in Helm values
      run: |
        cd flux-config
        sed -i "s/^  tag: .*/  tag: ${{ needs.build-and-push-docker.outputs.sha }}/" ./apps/dev/password-generator/values.yaml

    - name: Push changes to a new branch
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "username@users.noreply.github.com"
        git checkout -b update-image-${{ needs.build-and-push-docker.outputs.sha }}
        git status
        # git add .
        # git commit -m "Update image tag to ${{ needs.build-and-push-docker.outputs.sha }}"
        # git push origin update-image-${{ needs.build-and-push-docker.outputs.sha }}
